### ISSUE TITLE
undefined method `name' for #<JIRA::Resource::User:0x00007fdbab0bb128>

### ISSUE THREAD

**Issue by nathan-fiscaletti** [keepcosmos/terjira#89]
I try to look at the summary for an issue and instead receive this error:

```
$ jira issue 'TODO-210'
undefined method `name' for #<JIRA::Resource::User:0x00007fdbab0bb128>
```

**Comment by nathan-fiscaletti** [comment]
This may have something to do with using Google OAuth for all of our Jira users.

**Comment by nicklan** [comment]
I'm also running into this, started a few days ago for me. I'm also using google oauth

**Comment by MadBomber** [comment]
i get it too.

**Comment by ezracelli** [comment]
+1, also using Google OAuth (used an API key to `jira login`)

**Comment by mrusme** [comment]
I'm running terjira (0.4.5) and this issue still occurs. Anyone else having trouble?

**Comment by skrshisode** [comment]
I'm running terjira (0.4.5). The issue still exists. But it could because of some other reason. When I run `jira issue ls --issuetype --assignee` it throws an error after I select required params:
`.gem/ruby/2.7.0/gems/terjira-0.4.5/lib/terjira/client/issue.rb:10: warning: deprecated Object#=~ is called on JIRA::Resource::User; it always returns nil
Empty`

**Comment by terrymunro** [comment]
+1, also running 0.4.5, getting both:
- ``undefined method `name` for #<JIRA::Resource::User...>``
- `...10: warning: deprecated Object#=~ is called on JIRA::Resource::User; it always returns nil Empty` <- though this is just a warning, it is always returning empty.
